# Generated by Django 4.1.2 on 2024-06-09 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensual', 'Subscripción Mensual'), ('anual', 'Subscripción Anual')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_usu', models.CharField(max_length=20)),
                ('contrasenna_usu', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_noticia', models.CharField(max_length=100)),
                ('subtitulo_noticia', models.CharField(max_length=50)),
                ('imagen_noticia', models.ImageField(upload_to='noticiasMedia/')),
                ('descImg_noticia', models.CharField(max_length=50)),
                ('cuerpo_noticia', models.TextField()),
                ('nom_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Noticias.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarjeta', models.CharField(max_length=255)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('fecha_expiracion', models.DateField()),
                ('codigo_seguridad', models.CharField(max_length=3)),
                ('direccion_envio', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos_adicionales', models.ManyToManyField(blank=True, to='Noticias.productoadicional')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Noticias.suscripcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Noticias.usuario')),
            ],
        ),
    ]
